version: '3.8'
services:
  app:
    build: .
    command: /bin/bash -c "make install &&
                           make run"
    environment:
      - PORT=8000
    ports:
      - 8000:8000
    volumes:
      - .:/code
      - ./data:/data
  app-bash:
    build: .
    command: /bin/bash -c "make install &&
                           /bin/bash"
    environment:
      - PORT=8000
    ports:
      - 8000:8000
    volumes:
      - .:/code
      - ./data:/data
  app-test:
    build: .
    command: /bin/bash -c "make install &&
                           make test"
    environment:
      - PORT=8000
    ports:
      - 8000:8000
volumes:
  data: {}
