# Generated by Django 4.2.4 on 2023-08-12 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20221205_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 12, 18, 32, 18, 236750)),
            preserve_default=False,
        ),
    ]
