# Generated by Django 4.2.11 on 2024-05-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='creation_date',
            new_name='date_created',
        ),
    ]
